# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    displayName: My First Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo my first Build job

- stage: deploy
  jobs:
  - deployment: DeployWeb	         # track deployments on the environment	
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-16.04'
    environment: 'smarthotel-dev'  # creates an environment if it doesn’t exist
    strategy: 
      runOnce:                     # default deployment strategy, more coming…
        deploy:                    
          steps:
          - script: echo my first deployment

